server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: Test12345
      database: spring-boot-mongodb
      authentication-database: admin